shlex: WIP: mostly passing Python compatibility tests
Failing 1 Posix test that appears to be due to the handling of words:
":" and ";".

```sh
$ go test -run TestPythonCompat_Posix
--- FAIL: TestPythonCompat_Posix (0.00s)
    shlex_test.go:177: ":-) ;-)":
        	got:  [")" ";" ")"]
        	want: [":-)" ";-)"]
```