WIP: shlex: slightly fix comment handling (still broken, but better)
Slightly fix the handling of comments (basically, revert the last
change).

TODO: this still needs to be fixed

```sh
--- FAIL: TestPythonCompat_NoPosix (0.00s)
    shlex_test.go:154: "foo#bar\nbaz":
        	got:  ["foobaz"]
        	want: ["foo#bar" "baz"]
```